---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Include ednz_cloud.utils.manage_repositories"
      ansible.builtin.include_role:
        name: "ednz_cloud.utils.manage_repositories"
      vars:
        manage_repositories_enable_default_repo: true
        manage_repositories_enable_custom_repo: true
        manage_repositories_custom_repo:
          - name: docker
            uri: "https://download.docker.com/linux/ubuntu"
            comments: "hashicorp repository"
            types:
              - deb
            suites:
              - "{{ ansible_distribution_release }}"
            components:
              - stable
            signed_by: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg "

    - name: "Install custom packages"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - jq
