---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Test: packages mariadb-server, apache2, docker-ce:5:28.1.0-1"
      block:
        - name: "Get packages facts"
          ansible.builtin.package_facts:
            manager: auto

        - name: "Verify packages mariadb-server, apache2, docker-ce:5:28.1.0-1"
          ansible.builtin.assert:
            that:
              - "ansible_facts.packages['mariadb-server'][0]['name'] == 'mariadb-server'"
              - "ansible_facts.packages['apache2'][0]['name'] == 'apache2'"
              - "ansible_facts.packages['docker-ce'][0]['name'] == 'docker-ce'"
              - "'5:28.1.0-1' in ansible_facts.packages['docker-ce'][0]['version']"
              - "ansible_facts.packages['jq'] is not defined"
              - "ansible_facts.packages['vim'] is not defined"
