---
# meta file for manage_repositories
galaxy_info:
  namespace: "ednz_cloud"
  role_name: "manage_repositories"
  author: "Bertrand Lanson"
  description: "Repository management for debian-based distros."
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - "ubuntu"
    - "debian"
    - "repositories"
    - "packages"

dependencies: []
