---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Test: file /etc/default/nginx"
      block:
        - name: "Stat file /etc/default/nginx"
          ansible.builtin.stat:
            path: "/etc/default/nginx"
          register: stat_etc_default_nginx

        - name: "Slurp file /etc/default/nginx"
          ansible.builtin.slurp:
            src: "/etc/default/nginx"
          register: slurp_etc_default_nginx

        - name: "Verify file /etc/default/nginx"
          vars:
            nginx_expected_env_file: |

          ansible.builtin.assert:
            that:
              - stat_etc_default_nginx.stat.exists
              - stat_etc_default_nginx.stat.isreg
              - stat_etc_default_nginx.stat.pw_name == 'root'
              - stat_etc_default_nginx.stat.gr_name == 'root'
              - stat_etc_default_nginx.stat.mode == '0600'
              - (slurp_etc_default_nginx.content | b64decode | trim) ==
                (nginx_expected_env_file | trim)

    - name: "Test: quadlet file /etc/containers/systemd/nginx.container"
      block:
        - name: "Stat file /etc/containers/systemd/nginx.container"
          ansible.builtin.stat:
            path: "/etc/containers/systemd/nginx.container"
          register: stat_etc_containers_systemd_nginx_container

        - name: "Slurp file /etc/containers/systemd/nginx.container"
          ansible.builtin.slurp:
            src: "/etc/containers/systemd/nginx.container"
          register: slurp_etc_containers_systemd_nginx_container

        - name: "Verify quadlet file /etc/containers/systemd/nginx.container"
          vars:
            nginx_expected_container_file: |
              [Container]
              ContainerName=nginx
              EnvironmentFile=/etc/default/nginx
              Image=docker.io/nginx

              [Service]
              Restart=always
              RestartSec=10s

              [Install]
              WantedBy=multi-user.target
          ansible.builtin.assert:
            that:
              - stat_etc_containers_systemd_nginx_container.stat.exists
              - stat_etc_containers_systemd_nginx_container.stat.isreg
              - stat_etc_containers_systemd_nginx_container.stat.pw_name == 'root'
              - stat_etc_containers_systemd_nginx_container.stat.gr_name == 'root'
              - stat_etc_containers_systemd_nginx_container.stat.mode == '0644'
              - (slurp_etc_containers_systemd_nginx_container.content | b64decode) == nginx_expected_container_file

    - name: "Test: service nginx"
      block:
        - name: "Get service facts"
          ansible.builtin.service_facts:

        - name: "Verify service nginx"
          ansible.builtin.assert:
            that:
              - ansible_facts.services['nginx.service'] is defined
              - ansible_facts.services['nginx.service']['state'] == 'running'

    - name: "Test: files in /opt/files"
      block:
        - name: "Stat /opt/files"
          ansible.builtin.stat:
            path: "/opt/files"
          register: stat_opt_files

        - name: "Find all files in /opt/files"
          ansible.builtin.find:
            paths: "/opt/files"
            recurse: true
            file_type: any
          register: found_opt_files

        - name: "Verify /opt/files directory and expected files"
          vars:
            expected_files:
              - "/opt/files/file.yml"
              - "/opt/files/dir"
              - "/opt/files/dir/test1"
              - "/opt/files/dir/test2.yml"
              - "/opt/files/dir/test3.yml"
              - "/opt/files/dir/dir1"
              - "/opt/files/dir/dir1/file.yml"
          ansible.builtin.assert:
            that:
              - stat_opt_files.stat.exists
              - stat_opt_files.stat.isdir
              - stat_opt_files.stat.pw_name == 'root'
              - stat_opt_files.stat.gr_name == 'root'
              - expected_files | difference(found_opt_files.files | map(attribute='path') | list) | length == 0
