---
namespace: ednz_cloud
name: utils
version: 0.6.0
readme: README.md
authors:
  - Bertrand Lanson <bertrand.lanson@protonmail.com>
description: A collection for all ednz_cloud utilities.
license: ["MIT"]
license_file: "LICENSE"
tags: ["tools", "utilities", "docker", "containers", "systems", "dns", "linux"]
dependencies:
  community.docker: ">4.6.0"
  ansible.posix: ">1.6.0"
  community.general: ">10.5.0"
repository: https://git.ednz.fr/ansible-collections/ednz_cloud.utils.git
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore:
  - .gitea**
# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null
