---
# vars file for motd
motd_directory_path: /etc/update-motd.d
motd_ascii_file: 00-ascii-logo
motd_sysinfo_file: 10-sysinfo
motd_production_warning_file: 99-production-warning
motd_filenames:
  - "{{ motd_ascii_file }}"
  - "{{ motd_sysinfo_file }}"
motd_color_map:
  black: "[0;30m"
  red: "[0;31m"
  green: "[0;32m"
  yellow: "[1;33m"
  blue: "[0;34m"
  purple: "[0;35m"
  cyan: "[0;36m"
  light_cyan: "[1;36m"
  white: "[1;37m"
