---
# meta file for manage_netplan
galaxy_info:
  namespace: "ednz_cloud"
  role_name: "manage_netplan"
  author: "Bertrand Lanson"
  description: "Install and configure network interfaces using netplan for debian-based distros."
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - "ubuntu"
    - "debian"
    - "network"
    - "netplan"

dependencies: []
