---
name: pull-request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  commit-check:
    name: Check commit compliance
    uses: https://git.ednz.fr/github-actions/library/.gitea/workflows/cz-pull-request-check.yml@fix/workflows
