name: Unit tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  unit-source:
    uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main
