---
manage_repositories_enable_default_repo: true
manage_repositories_enable_custom_repo: true
manage_repositories_custom_repo:
  - name: docker
    uri: "https://download.docker.com/linux/{{ ansible_distribution|lower }}"
    comments: "{{ ansible_distribution|lower }} docker repository"
    types:
      - deb
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - stable
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
  - name: hashicorp
    uri: "https://apt.releases.hashicorp.com"
    comments: "hashicorp repository"
    types:
      - deb
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - main
    signed_by: "https://apt.releases.hashicorp.com/gpg"
