---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Include ednz_cloud.utils.install_docker"
      ansible.builtin.include_role:
        name: ednz_cloud.utils.install_docker
      vars:
        install_docker_python_packages: true

    - name: "Create extra files directory"
      ansible.builtin.file:
        path: "/opt/files"
        state: directory
        owner: root
        group: root
        mode: "0775"
