---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Test: file /etc/default/nginx_container"
      block:
        - name: "Stat file /etc/default/nginx_container"
          ansible.builtin.stat:
            path: "/etc/default/nginx_container"
          register: stat_etc_default_nginx_container

        - name: "Slurp file /etc/default/nginx_container"
          ansible.builtin.slurp:
            src: "/etc/default/nginx_container"
          register: slurp_etc_default_nginx_container

        - name: "Verify file /etc/default/nginx_container"
          vars:
            nginx_expected_env_file: |

          ansible.builtin.assert:
            that:
              - stat_etc_default_nginx_container.stat.exists
              - stat_etc_default_nginx_container.stat.isreg
              - stat_etc_default_nginx_container.stat.pw_name == 'root'
              - stat_etc_default_nginx_container.stat.gr_name == 'root'
              - stat_etc_default_nginx_container.stat.mode == '0600'
              - (slurp_etc_default_nginx_container.content | b64decode | trim) ==
                (nginx_expected_env_file | trim)

    - name: "Test: service nginx_container"
      block:
        - name: "Get service nginx_container"
          ansible.builtin.service_facts:

        - name: "Stat file /etc/systemd/system/nginx_container.service"
          ansible.builtin.stat:
            path: "/etc/systemd/system/nginx_container.service"
          register: stat_etc_systemd_system_nginx_container_service

        - name: "Slurp file /etc/systemd/system/nginx_container.service"
          ansible.builtin.slurp:
            src: "/etc/systemd/system/nginx_container.service"
          register: slurp_etc_systemd_system_nginx_container_service

        - name: "Verify service nginx_container"
          vars:
            nginx_expected_service_file: |
              [Unit]
              After=docker.service
              PartOf=docker.service
              Requires=multi-user.target

              [Service]
              EnvironmentFile=/etc/default/nginx_container
              ExecReload=/usr/local/bin/docker kill --signal=SIGHUP nginx
              ExecStart=/usr/local/bin/docker run --name nginx \
              --rm \
              --env-file /etc/default/nginx_container \
              nginx

              ExecStartPre=-/usr/local/bin/docker rm -f nginx
              ExecStop=/usr/local/bin/docker stop nginx
              Restart=always
              RestartSec=10s
              SyslogIdentifier=nginx

              [Install]
              WantedBy=multi-user.target
          ansible.builtin.assert:
            that:
              - stat_etc_systemd_system_nginx_container_service.stat.exists
              - stat_etc_systemd_system_nginx_container_service.stat.isreg
              - stat_etc_systemd_system_nginx_container_service.stat.pw_name == 'root'
              - stat_etc_systemd_system_nginx_container_service.stat.gr_name == 'root'
              - stat_etc_systemd_system_nginx_container_service.stat.mode == '0644'
              - (slurp_etc_systemd_system_nginx_container_service.content|b64decode) == nginx_expected_service_file
              - ansible_facts.services['nginx_container.service'] is defined
              - ansible_facts.services['nginx_container.service']['source'] == 'systemd'
              - ansible_facts.services['nginx_container.service']['state'] == 'running'
              - ansible_facts.services['nginx_container.service']['status'] == 'enabled'

    - name: "Test: files in /opt/files"
      block:
        - name: "Stat /opt/files"
          ansible.builtin.stat:
            path: "/opt/files"
          register: stat_opt_files

        - name: "Find all files in /opt/files"
          ansible.builtin.find:
            paths: "/opt/files"
            recurse: yes
            file_type: any
          register: found_opt_files

        - name: "Verify /opt/files directory and expected files"
          vars:
            expected_files:
              - "/opt/files/file.yml"
              - "/opt/files/dir"
              - "/opt/files/dir/test1"
              - "/opt/files/dir/test2.yml"
              - "/opt/files/dir/test3.yml"
              - "/opt/files/dir/dir1"
              - "/opt/files/dir/dir1/file.yml"
          ansible.builtin.assert:
            that:
              - stat_opt_files.stat.exists
              - stat_opt_files.stat.isdir
              - stat_opt_files.stat.pw_name == 'root'
              - stat_opt_files.stat.gr_name == 'root'
              - expected_files | difference(found_opt_files.files | map(attribute='path') | list) | length == 0
